### ISSUE TITLE
Consistent tile padding for small and large screens

### ISSUE THREAD

**Issue by jofas** [jofas/jofas.github.io#56]
remove every occurrence of any `lg:pb-*` class from `static/index.html`, starting with line 232:

https://github.com/jofas/jofas.github.io/blob/ae591eed0c2585b1626fefeddb069f7631614c4a/static/index.html#L232

ending at line 646:

https://github.com/jofas/jofas.github.io/blob/ae591eed0c2585b1626fefeddb069f7631614c4a/static/index.html#L646

**Comment by RajeevDash007** [comment]
I will do it, assign me
